### ISSUE TITLE
Issue on page /modules/module4.html

### ISSUE THREAD

**Issue by j-strandberg** [tu-delft-library/rdm101-book#2]
Small error in the Data Organisation test: For Question 5 "Consistency is not relevant in data organisation", the correct answer gives the incorrect notification text.

![Picture1](https://github.com/tu-delft-library/rdm101-book/assets/136434534/8a6e254a-3378-4214-9b47-c5359030f182)

**Comment by carlosug** [comment]
Hi @j-strandberg, thank you so much for opening the issue, and for spotting this. We've just addressed it and added the correct feedback: 
<img width="808" alt="image" src="https://github.com/tu-delft-library/rdm101-book/assets/50459069/22068f7b-69c0-484d-81eb-b813a7a55ef2">
